### ISSUE TITLE
Using koa-resource-router in conjunction with koa-router

### ISSUE THREAD

**Issue by rtm** [alexmingoia/koa-resource-router#14]
Sorry if this is not the right place to raise this issue.

I want to use koa-resource-router in conjunction with koa-router to be able to create a route composed of resources, that can be "mounted" on the app. The basic idea is to do something like

```
var router = new Router();
var resource = new Resource(...);
router.use(resource);       //. <== can't do this now
app.use(mount(mountPoint, router));
```

I have the feeling these is some obvious way to do this but I can't figure out what it is.

**Comment by alexmingoia** [comment]
I'm not sure what you mean by a "route composed of resources"? A resource has many routes. A router has many routes. Both expose their routing middleware via `.middleware()`.

``` javascript
var Router = require('koa-router');
var Resource = require('koa-resource-router');

var app = require('koa')();
var books = new Resource(...);
var authors = new Resource(...);
var router = new Router();

router.get('/login', function *() {...});

app
  .use(books.middleware())
  .use(authors.middleware())
  .use(router.middleware());
```

**Comment by rtm** [comment]
Thanks for your answer and sorry for the imprecision in my question. What I meant was, a "router composed of multiple resources", so that I can mount that router at a particular mount point such as `apiV1`.

**Comment by alexmingoia** [comment]
Here's another example where resources are protected by auth middleware and composed using `koa-compose`:

``` javascript
var compose = require('koa-compose');
var Router = require('koa-router');
var Resource = require('koa-resource-router');

var app = require('koa')();

var books = new Resource(...);
var authors = new Resource(...);

var publicRouter = new Router();
publicRouter.get('/login', function *() {...});
publicRouter.get('/about', function *() {...});

var publicRoutes = publicRouter.middleware();
var privateRoutes = compose([
  authMiddleware(),
  books.middleware(),
  authors.middleware()
]);

app
  .use(publicRoutes)
  .use(privateRoutes);
```

**Comment by alexmingoia** [comment]
Resources are their own routers. So to mount multiple resources at a given path just use `koa-mount`. No need to muck with koa-router at all. If you want to combine the resources and router middlewares into a single middleware, use `koa-compose` and then mount that at a path using `koa-mount`.
