### ISSUE TITLE
Nesting URLs Example in Readme

### ISSUE THREAD

**Issue by rattrayalex** [alexmingoia/koa-resource-router#15]
Hi, 

koa-resource-router looks great. I found the section on nesting in the docs a bit ambiguous. I assume it generates something like this: `/forums/:id/threads/:id` but I'm not sure. I'm also not sure how the forum id will get passed to the relevant handlers. 

Just a small docs change would be great!

**Comment by alexmingoia** [comment]
`/forums/:id/threads/:id` is correct.
